name: Publish to PyPi
description: Publish to PyPi
inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.6'
  publish:
    description: 'Publish'
    required: false
    default: 'test+pypi'
    type: choice
    options:
      - 'pypi'
      - 'test'
      - 'test+pypi'
      - 'auto'        # alias for test+pypi
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies for building package
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
      shell: bash
    - name: Build a binary wheel and a source tarball
      run: |
        python setup.py sdist bdist_wheel
      shell: bash
    - name: Publish distribution 📦 to Test PyPI
      if: |
        inputs.publish == 'test' || 
        inputs.publish == 'test+pypi' || 
        inputs.publish == 'auto'
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: |
        inputs.publish == 'pypi' || 
        inputs.publish == 'test+pypi' || 
        inputs.publish == 'auto'
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
        repository_url: https://pypi.org